0x0C

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,8 +1,23 @@
 #!/usr/bin/env bash
-# this installs nginx and also configures it on a remote server
+# This script installs the Nginx web server and configures the initial "Hello
+# world" page.
 
-apt-get -y update
-apt-get -y install nginx
-ufw allow 'Nginx HTTP'
-echo 'Hello world!' > /var/www/html/index.nginx-debian.html
+if [[ $EUID -ne 0 ]]; then
+  echo "ERROR: You need to be root to run this script" 1>&2
+  exit 1
+fi
+
+# Update the package list and install Nginx
+apt-get update
+apt-get install -y nginx
+
+# Create the default "Hello world" page
+echo "Hello World!" > /var/www/html/index.html
+
+# Start the Nginx service
 service nginx start
+
+if [[ ! $? ]]; then
+  echo "ERROR: Failed to start Nginx" 1>&2
+  exit 1
+fi
diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,8 +1,33 @@
 #!/usr/bin/env bash
-# install nginx
+# This script installs the Nginx web server and configures the initial "Hello
+# world" page.
 
-sudo apt-get update
-sudo apt-get -y install nginx
-echo "Hello World" | sudo tee -a /var/www/html/index.html
-sudo sed -i '36a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
-sudo service nginx restart
+if [[ $EUID -ne 0 ]]; then
+  echo "ERROR: You need to be root to run this script" 1>&2
+  exit 1
+fi
+
+# Update the package list and install Nginx
+apt-get update
+apt-get install -y nginx
+
+# Create the default "Hello world" page
+echo "Hello World!" > /var/www/html/index.html
+
+echo -e "\tserver_name _;
+\tlocation /redirect_me {
+\t\treturn 301 https://lzcorp-landing-page.vercel.app/;
+\t}" > /tmp/new_config
+
+sed -i '/server_name _;/{
+    r /tmp/new_config
+    d
+}' /etc/nginx/sites-available/default
+
+# Start the Nginx service
+service nginx restart
+
+if [[ ! $? ]]; then
+  echo "ERROR: Failed to start Nginx" 1>&2
+  exit 1
+fi
